version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: survivor_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: survivor_db
      MYSQL_USER: survivor_user
      MYSQL_PASSWORD: survivor_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: .
    container_name: survivor_backend
    restart: always
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: survivor_user
      DB_PASSWORD: survivor_pass
      DB_NAME: survivor_db
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "dev"]

volumes:
  db_data:
